name: Build

on:
  workflow_dispatch:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:     [ubuntu-latest]
        mode:   [newlib, linux, musl, uclibc]
        target: [rv32gc-ilp32d, rv64gc-lp64d]
        compiler: [gcc, llvm]
        exclude:
          - mode: musl
            compiler: llvm
          - mode: uclibc
            compiler: llvm
    steps:
      - name: Remove unneeded frameworks to recover disk space
        run: |
          echo "-- Before --"
          df -h
          sudo rm -rf /usr/local/bin/aliyun
          sudo apt-get purge -y apache2 azure-cli podman buildah skopeo firefox google-chrome-stable google-cloud-cli heroku temurin-*-jdk ant ant-optional kubectl microsoft-edge-stable apt-transport-https mono-complete nuget mssql-tools unixodbc-dev mysql-client mysql-server libmysqlclient-dev nginx php php-pear snmp postgresql-* libpq-dev powershell r-base ruby-full
          sudo apt-get purge -y '^dotnet-.*'
          sudo dpkg -r session-manager-plugin
          sudo apt-get autoremove --purge -y
          sudo apt-get clean
          sudo rm -rf /usr/local/bin/aws
          sudo rm -rf /usr/local/bin/aws_completer
          sudo rm -rf /usr/local/aws-cli
          sudo rm -rf /usr/local/bin/sam
          sudo rm -rf /usr/local/aws-sam-cli
          sudo rm -rf /usr/local/bin/azcopy
          sudo rm -rf /usr/local/bin/azcopy10
          sudo rm -rf /opt/az/azcliextensions
          sudo rm -rf /usr/local/bin/bazel
          sudo rm -rf /usr/local/bin/bicep
          sudo rm -rf /opt/hostedtoolcache
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/bin/rebar3
          sudo rm -rf /usr/local/share/gecko_driver
          sudo rm -rf /usr/local/share/chromedriver-linux64
          sudo rm -rf /usr/local/share/chromium
          sudo rm -rf /usr/local/.ghcup/
          sudo rm -rf /home/linuxbrew
          sudo rm -rf /usr/share/apache-maven-*
          sudo rm -rf /usr/share/gradle
          sudo rm -rf /usr/local/julia*
          sudo rm -rf /usr/share/kotlinc
          sudo rm -rf /usr/local/bin/minikube
          sudo rm -rf /usr/local/share/edge_driver
          sudo rm -rf /usr/local/lib/node_modules/*
          sudo rm -rf /usr/local/bin/oc
          sudo rm -rf /usr/local/bin/oras
          sudo rm -rf /usr/share/java/selenium-server-*
          sudo rm -rf /usr/share/swift
          sudo rm -rf /usr/local/share/vcpkg
          sudo rm -rf /usr/local/lib/android
          echo "-- After --"
          df -h

      - uses: actions/checkout@v4

      - name: install dependencies
        run: sudo ./.github/setup-apt.sh

      - name: build toolchain
        run: |
          TARGET_TUPLE=($(echo ${{ matrix.target }} | tr "-" "\n"))
          BUILD_TOOLCHAIN="./configure --prefix=/opt/riscv --with-arch=${TARGET_TUPLE[0]} --with-abi=${TARGET_TUPLE[1]}"
          if [ "${{ matrix.compiler }}" == "llvm" ]; then # build toolchain with llvm
            $BUILD_TOOLCHAIN --enable-llvm
          else
            $BUILD_TOOLCHAIN
          fi
          sudo make -j $(nproc) ${{ matrix.mode }}

      - name: make report
        if: |
          matrix.os == 'ubuntu-24.04'
          && (matrix.mode == 'linux' || matrix.mode == 'newlib')
          && matrix.compiler == 'gcc'
        run: |
          sudo make report-${{ matrix.mode }} -j $(nproc)

      - name: recover space
        run: |
          sudo du -hs / 2> /dev/null || true
          sudo rm -rf binutils dejagnu gcc gdb glibc llvm musl newlib pk qemu spike uclibc-ng || true
          sudo du -hs / 2> /dev/null || true

      - name: tarball build
        run: tar czvf riscv.tar.gz -C /opt/ riscv/

      - name: generate prebuilt toolchain name
        id:   toolchain-name-generator
        run: |
          if [[ "${{ matrix.target }}" == *"32"* ]]; then BITS=32; else BITS=64; fi
          case "${{ matrix.mode }}" in
            "linux")
              MODE="glibc";;
            "musl")
              MODE="musl";;
            "uclibc")
              MODE="uclibc-ng";;
            *)
              MODE="elf";;
          esac
          echo "TOOLCHAIN_NAME=riscv$BITS-$MODE-${{ matrix.os }}-${{ matrix.compiler }}-nightly" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.toolchain-name-generator.outputs.TOOLCHAIN_NAME }}
          path: riscv.tar.gz

  test-sim:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:     [ubuntu-24.04]
        mode:   [newlib]
        target: [rv64gc-lp64d]
        sim:    [spike]
    steps:
      - name: Remove unneeded frameworks to recover disk space
        run: |
          echo "-- Before --"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          echo "-- After --"
          df -h

      - uses: actions/checkout@v4

      - name: install dependencies
        run: sudo ./.github/setup-apt.sh

      - name: build toolchain
        run: |
          TARGET_TUPLE=($(echo ${{ matrix.target }} | tr "-" "\n"))
          ./configure --prefix=/opt/riscv --with-arch=${TARGET_TUPLE[0]} --with-abi=${TARGET_TUPLE[1]} --with-sim=${{ matrix.sim }}
          make -j $(nproc) ${{ matrix.mode }}

      - name: make report
        run: make report-${{ matrix.mode }} -j $(nproc)

  build-multilib:
    if: ${{ false }} # Disable until multilib errors are triaged
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os:     [ubuntu-24.04]
        mode:   [newlib, linux]
        target: [rv64gc-lp64d]
    steps:
      - name: Remove unneeded frameworks to recover disk space
        run: |
          echo "-- Before --"
          df -h
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          echo "-- After --"
          df -h

      - uses: actions/checkout@v4

      - name: install dependencies
        run: sudo ./.github/setup-apt.sh

      - name: build toolchain
        run: |
          TARGET_TUPLE=($(echo ${{ matrix.target }} | tr "-" "\n"))
          ./configure --prefix=/opt/riscv --with-arch=${TARGET_TUPLE[0]} --with-abi=${TARGET_TUPLE[1]} --enable-multilib
          sudo make -j $(nproc) ${{ matrix.mode }}

      - name: make report
        run: |
          sudo make report-${{ matrix.mode }} -j $(nproc)

      - name: tarball build
        run: tar czvf riscv.tar.gz -C /opt/ riscv/

      - name: generate prebuilt toolchain name
        id:   toolchain-name-generator
        run: |
          if [[ "${{ matrix.target }}" == *"32"* ]]; then BITS=32; else BITS=64; fi
          case "${{ matrix.mode }}" in
            "linux")
              MODE="glibc";;
            "musl")
              MODE="musl";;
            "uclibc")
              MODE="uclibc-ng";;
            *)
              MODE="elf";;
          esac
          echo "TOOLCHAIN_NAME=riscv$BITS-$MODE-${{ matrix.os }}-multilib-nightly" >> $GITHUB_OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: ${{ steps.toolchain-name-generator.outputs.TOOLCHAIN_NAME }}
          path: riscv.tar.gz
